title: Kristen's Cybersecurity Portfolio
description: "Cybersecurity portfolio highlighting my projects in system hardening, monitoring, and incident analysis/reporting"
baseurl: ""
url: https://cynthetic13.github.io
github_username: Cynthetic13

# Build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  
navigation:
  - text: Home
    url: /
  - text: Homelab
    url: /homelab/